#!/usr/bin/env python3
"""
Analyze the ProcMon CSV data using SIEM dashboard logic
"""

import csv
from datetime import datetime
from collections import defaultdict

# Read the CSV
logs = []
with open('procmon_analysis.csv', 'r') as f:
    reader = csv.DictReader(f)
    for row in reader:
        logs.append(row)

print("=" * 80)
print("🚨 SIEM ANALYSIS REPORT - Process Monitor Log")
print("=" * 80)
print()

# Overall stats
print("📈 OVERALL STATISTICS")
print("-" * 80)
print(f"Total Events Analyzed: {len(logs)}")
print(f"Time Range: {logs[0]['timestamp']} to {logs[-1]['timestamp']}")
print(f"Process: {logs[0]['user']}")
print(f"Source IP: {logs[0]['ip_address']}")
print()

# Honeyfile Detection
print("🍯 HONEYFILE ALERTS (CRITICAL)")
print("-" * 80)
honeyfil_alerts = [log for log in logs if log['is_honeyfil'] == 'true']
unique_honeyfiles = set(log['file_path'] for log in honeyfil_alerts)

print(f"Total Honeyfile Access Events: {len(honeyfil_alerts)}")
print(f"Unique Honeyfiles Accessed: {len(unique_honeyfiles)}")
print()

if honeyfil_alerts:
    print("⚠️  ALERT: The following HONEYFILES were accessed:")
    for i, filepath in enumerate(unique_honeyfiles, 1):
        filename = filepath.split('\\')[-1]
        access_count = sum(1 for log in honeyfil_alerts if log['file_path'] == filepath)
        print(f"   {i}. {filename}")
        print(f"      Path: {filepath}")
        print(f"      Accesses: {access_count}")
        print(f"      Severity: CRITICAL")
        print()

# User Behavior Analysis
print("🔍 USER BEHAVIOR ANALYSIS")
print("-" * 80)

# Time-based analysis
print("⏰ Access Time Analysis:")
for log in logs:
    timestamp = datetime.fromisoformat(log['timestamp'])
    hour = timestamp.hour

    if hour < 8 or hour > 18:
        print(f"   ⚠️  OUT-OF-HOURS ACCESS DETECTED")
        print(f"      Time: {timestamp.strftime('%H:%M:%S')}")
        print(f"      File: {log['file_path'].split(chr(92))[-1]}")
        print(f"      Severity: HIGH")
        break
else:
    print(f"   ✓ All access occurred during office hours (8 AM - 6 PM)")
print()

# File access patterns
print("📁 File Access Patterns:")
file_access = defaultdict(int)
for log in logs:
    filename = log['file_path'].split('\\')[-1]
    file_access[filename] += 1

for filename, count in sorted(file_access.items(), key=lambda x: x[1], reverse=True):
    is_honeyfil = any(log['file_path'].endswith(filename) and log['is_honeyfil'] == 'true' for log in logs)
    status = "🍯 HONEYFIL" if is_honeyfil else "Normal"
    print(f"   • {filename}: {count} accesses [{status}]")
print()

# Risk Assessment
print("⚡ RISK ASSESSMENT")
print("-" * 80)
print(f"User: {logs[0]['user']}")
print(f"Risk Level: {'🔴 CRITICAL (HIGH)' if len(honeyfil_alerts) > 0 else '🟢 LOW'}")
print()
print(f"Reasons:")
if honeyfil_alerts:
    print(f"   • Accessed {len(unique_honeyfiles)} honeyfils (CRITICAL INDICATOR)")
    print(f"   • Multiple attempts to access sensitive decoy files")
    print(f"   • Pattern suggests reconnaissance or data exfiltration attempt")
else:
    print(f"   • Normal file access patterns")
print()

# Recommendations
print("💡 RECOMMENDATIONS")
print("-" * 80)
if honeyfil_alerts:
    print("   1. 🚨 IMMEDIATE ACTION REQUIRED:")
    print("      - Investigate the user/process immediately")
    print("      - Check for data exfiltration")
    print("      - Review user's recent activity")
    print("      - Consider isolating the system")
    print()
    print("   2. 🔒 SECURITY MEASURES:")
    print("      - Verify if this is authorized security testing")
    print("      - Check for malware/unauthorized access")
    print("      - Review access logs from other systems")
    print("      - Implement additional monitoring")
    print()
    print("   3. 📝 DOCUMENTATION:")
    print("      - Create incident report")
    print("      - Document all accessed files")
    print("      - Preserve evidence for investigation")
else:
    print("   • Continue monitoring user activity")
    print("   • No immediate action required")
print()

print("=" * 80)
print("Analysis Complete - Generated by SIEM Dashboard")
print("=" * 80)
